version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: erp_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:15-alpine
    container_name: seasons_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: seasons_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    # REMOVED PORTS: Only Nginx can talk to the backend now

  frontend:
    build: ./frontend
    container_name: seasons_frontend
    environment:
      - VITE_API_URL=/api
    restart: always
    # REMOVED PORTS: Only Nginx can talk to the frontend now