"""baseline setup

Revision ID: ad51c367ef8a
Revises: 
Create Date: 2026-05-10 16:11:29.280420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad51c367ef8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username'),
    schema='auth'
    )
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_location_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_location_id'], ['inventory.locations.location_id'], ),
    sa.PrimaryKeyConstraint('location_id'),
    schema='inventory'
    )
    op.create_table('product_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['inventory.product_categories.category_id'], ),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name'),
    schema='inventory'
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_notes', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('banking_details', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id'),
    schema='inventory'
    )
    op.create_table('uoms',
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('uom_code', sa.String(length=50), nullable=False),
    sa.Column('uom_name', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uom_id'),
    sa.UniqueConstraint('uom_code'),
    schema='inventory'
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('max_payment_term', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    schema='sales'
    )
    op.create_table('pos_settings',
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('is_vat_enabled', sa.Boolean(), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('setting_id'),
    schema='sales'
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variant', sa.String(length=100), nullable=True),
    sa.Column('is_bundle', sa.Boolean(), nullable=True),
    sa.Column('units_per_bundle', sa.Integer(), nullable=True),
    sa.Column('tag_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_discount', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('net_price', sa.Numeric(precision=12, scale=2), server_default=sa.FetchedValue(), nullable=True),
    sa.Column('gross_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_discount', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('net_cost', sa.Numeric(precision=12, scale=2), server_default=sa.FetchedValue(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('base_uom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_uom_id'], ['inventory.uoms.uom_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('pid'),
    sa.UniqueConstraint('sku'),
    schema='inventory'
    )
    op.create_table('stock_transfers',
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=True),
    sa.Column('transfer_date', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('released_by_id', sa.Integer(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('bundle_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('has_discrepancy', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['inventory.locations.location_id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['released_by_id'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['inventory.locations.location_id'], ),
    sa.PrimaryKeyConstraint('transfer_id'),
    schema='inventory'
    )
    op.create_table('sales_headers',
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(), nullable=False),
    sa.Column('sales_invoice_id', sa.String(), nullable=True),
    sa.Column('delivery_receipt_id', sa.String(), nullable=True),
    sa.Column('register_id', sa.String(), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cashier_id'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['sales.customers.customer_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['inventory.locations.location_id'], ),
    sa.PrimaryKeyConstraint('sales_id'),
    sa.UniqueConstraint('idempotency_key'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_sales_headers_document_id'), 'sales_headers', ['document_id'], unique=True, schema='sales')
    op.create_index(op.f('ix_sales_sales_headers_sales_id'), 'sales_headers', ['sales_id'], unique=False, schema='sales')
    op.create_table('cost_layers',
    sa.Column('layer_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('ref_table', sa.String(length=100), nullable=True),
    sa.Column('ref_pk', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.products.product_id'], ),
    sa.PrimaryKeyConstraint('layer_id'),
    schema='inventory'
    )
    op.create_table('current_stocks',
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inventory.locations.location_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.products.product_id'], ),
    sa.PrimaryKeyConstraint('stock_id'),
    schema='inventory'
    )
    op.create_table('inventory_ledger',
    sa.Column('ledger_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('qty_change', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Enum('RECEIVE', 'SALE', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUST', name='ledger_reason', schema='inventory'), nullable=False),
    sa.Column('ref_table', sa.String(length=100), nullable=True),
    sa.Column('ref_pk', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inventory.locations.location_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.products.product_id'], ),
    sa.PrimaryKeyConstraint('ledger_id'),
    schema='inventory'
    )
    op.create_table('price_history',
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('old_tag_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_tag_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('old_net_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_net_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('old_gross_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_gross_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('old_net_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_net_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id'),
    schema='inventory'
    )
    op.create_table('product_category_link',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['inventory.product_categories.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id'),
    schema='inventory'
    )
    op.create_table('product_suppliers',
    sa.Column('sourcing_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('vendor_sku', sa.String(length=100), nullable=True),
    sa.Column('vendor_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['inventory.suppliers.supplier_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sourcing_id'),
    schema='inventory'
    )
    op.create_table('stock_transfer_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('bundling', sa.String(length=100), nullable=True),
    sa.Column('requested_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('released_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('received_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.products.product_id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['inventory.stock_transfers.transfer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id'),
    schema='inventory'
    )
    op.create_table('sales_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_flat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.products.product_id'], ),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.sales_headers.sales_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_sales_items_item_id'), 'sales_items', ['item_id'], unique=False, schema='sales')
    op.create_table('sales_payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.sales_headers.sales_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_sales_payments_payment_id'), 'sales_payments', ['payment_id'], unique=False, schema='sales')
    op.create_table('sales_returns',
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.sales_headers.sales_id'], ),
    sa.PrimaryKeyConstraint('return_id'),
    schema='sales'
    )
    op.create_table('sales_return_items',
    sa.Column('return_item_id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.products.product_id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['sales.sales_returns.return_id'], ),
    sa.PrimaryKeyConstraint('return_item_id'),
    schema='sales'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_return_items', schema='sales')
    op.drop_table('sales_returns', schema='sales')
    op.drop_index(op.f('ix_sales_sales_payments_payment_id'), table_name='sales_payments', schema='sales')
    op.drop_table('sales_payments', schema='sales')
    op.drop_index(op.f('ix_sales_sales_items_item_id'), table_name='sales_items', schema='sales')
    op.drop_table('sales_items', schema='sales')
    op.drop_table('stock_transfer_items', schema='inventory')
    op.drop_table('product_suppliers', schema='inventory')
    op.drop_table('product_category_link', schema='inventory')
    op.drop_table('price_history', schema='inventory')
    op.drop_table('inventory_ledger', schema='inventory')
    op.drop_table('current_stocks', schema='inventory')
    op.drop_table('cost_layers', schema='inventory')
    op.drop_index(op.f('ix_sales_sales_headers_sales_id'), table_name='sales_headers', schema='sales')
    op.drop_index(op.f('ix_sales_sales_headers_document_id'), table_name='sales_headers', schema='sales')
    op.drop_table('sales_headers', schema='sales')
    op.drop_table('stock_transfers', schema='inventory')
    op.drop_table('products', schema='inventory')
    op.drop_table('pos_settings', schema='sales')
    op.drop_table('customers', schema='sales')
    op.drop_table('uoms', schema='inventory')
    op.drop_table('suppliers', schema='inventory')
    op.drop_table('product_categories', schema='inventory')
    op.drop_table('locations', schema='inventory')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
